### PR TITLE
Update error message to indicate exact file missing

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/ci/issues/996

### CODE REVIEW

**Comment by KrauseFx** [comment]
Actually no, gonna update this

**Comment by KrauseFx** [comment]
Ready to be reviewed & merged from my side 👍

**Comment by KrauseFx** [comment]
@AndrewMcBurney why? I thought that not having this file will allow the CI to run just fine, right? It's not actually required to get the server running and use fastlane.ci. From what I understand, the list should contain the files that are absolutely necessary to get the CI running. Once a user edits one ENV variable through the UI the file will automatically be created

**Comment by taquitos** [comment]
@AndrewMcBurney I totally misunderstood how we used that list of files. I just synced with @KrauseFx and it makes sense to keep this file out of that list. 
I thought that this list was also used to generate the files, I didn't realize we generate this file only when needed.
So, in this case, we can leave it out of the `CONFIGURATION_FILES` list. Sorry for any confusion I caused here!

**Comment by KrauseFx** [comment]
And to complete the context, here's where we create the file for the user: https://github.com/fastlane/ci/blob/be64b5a12ac22f73c4a6ccf855aca2f3fbb19e23/app/services/configuration_repository_service.rb#L127

**Pull request merged**
