### PR TITLE
moving submodule projects into vendored gems

### PR DESCRIPTION
**Pull request by snatchev**
This PR makes the external submodule dependencies as vendored gems. The benefit is that we can take updates easier and have only 1 process for keeping dependencies up to date. Also, this opens the ability to not use submodules by using bundler's `:git` source. http://bundler.io/v1.12/git.html#gems-from-git-repositories

https://github.com/fastlane/TaskQueue/pull/7
https://github.com/fastlane/fastfile-parser/pull/9

These gems are not intended to be publicly available yet.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Uhh, why does this also move all the files?

**Comment by taquitos** [comment]
@KrauseFx I think it needs to be rebased on master. It looks like he might have made this PR on top of a previous commit

**Comment by taquitos** [comment]
Oh, or the previous PR merged into this branch

**Comment by snatchev** [comment]
Yes, I was expecting #345 to be merged into master first and then #350 to go on top of that. I broke them out so they could be reviewed independently.

**Comment by snatchev** [comment]
@taquitos rebased and it seems to pass tests for me. Let me know if there is a problem preventing a merge.

**Comment by taquitos** [comment]
@snatchev yeah, sorry about that. I didn't notice that the other PR was merging into this one. Feel free to call out what PRs should be merged first 👍

**Pull request merged**
