### PR TITLE
Dot Keys environment missing param

### PR DESCRIPTION
**Pull request by nakhbari**
Fixes the following error i was getting
```
bundler: failed to load command: rackup (/Users/nakhbari/.rbenv/versions/2.3.3/bin/rackup)
ArgumentError: wrong number of arguments (given 1, expected 2)
  /Users/nakhbari/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dotenv-2.4.0/lib/dotenv/environment.rb:7:in `initialize'
  /Users/nakhbari/Documents/fastlane/ci/app/services/dot_keys_variable_service.rb:34:in `new'
  /Users/nakhbari/Documents/fastlane/ci/app/services/dot_keys_variable_service.rb:34:in `reload_dot_env!'
```

### CODE REVIEW

**Comment by KrauseFx** [comment]
Yes, this is needed for the new bundler, I merged this back with https://github.com/fastlane/ci/pull/740 and was reverted back with https://github.com/fastlane/ci/pull/757

Looks like we're gonna have to do runtime checking to be compatible with both version of dot env or bundler 👍

**Comment by nakhbari** [comment]
@KrauseFx Not sure i understand. Is this sufficient to merge or is there another case we're missing?

**Comment by KrauseFx** [comment]
The change was introduced with version 2.3.0 or 2.4.0 (hard to tell from the GitHub UI) see https://github.com/bkeepers/dotenv/commit/7f82f73420bb46a06bb3a3e2052c3b3a1f34a0f5

@nakhbari I'll update your PR to make this work for everyone 👍

**Comment by KrauseFx** [comment]
Alright, PR is updated, and also added comments to the dot env repo https://github.com/bkeepers/dotenv/pull/345

**Comment by taquitos** [comment]
@KrauseFx are you sure `true` is the proper value there? Your PR that originally utilized that parameter had it set to `false` -> https://github.com/fastlane/ci/pull/740/files#diff-9ddf922c96bbb9ee3aeaeb8f2db5e1c6R33 .

**Comment by KrauseFx** [comment]
I'm not sure, it seems like either value is fine

**Comment by KrauseFx** [comment]
Merging this now

**Pull request merged**
