### PR TITLE
Add pre-check for Ruby version

### PR DESCRIPTION
**Pull request by Sherlouk**
Thought I'd keep it simple to dip my toes in the water, took logic from the [existing Fastlane action](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/ruby_version.rb) and what was already in the launch script

Not sure if there's a better location to store the constant?

### CODE REVIEW

**Comment by taquitos** [comment]
This seems totally reasonable to me. I don't think we use this constant in other places yet, so keeping it inline is 👌 
🎈:goat:

**Comment by Sherlouk** [comment]
Thanks for merging! 🙌 

Linking #120 as I forgot to, should leave it open though to track other system requirements 😄

**Comment by taquitos** [comment]
Thank you for helping us out here!

**Comment by KrauseFx** [comment]
🚀

**Pull request merged**
