### PR TITLE
Fix imports for DashboardComponent Tests

### PR DESCRIPTION
**Pull request by nakhbari**

### CODE REVIEW

**Comment by nakhbari** [comment]
These imports are getting annoying. Let's see if we can find a better method for common modules being imported.

**Comment by minuscorp** [comment]
Do you think this would work? https://angular.io/guide/sharing-ngmodules

**Comment by nakhbari** [comment]
@minuscorp yep that looks good. Maybe we could do one for just AngularMaterialShared. I think that's the one that has bulk.

**Comment by nakhbari** [comment]
Working on that right now^

**Comment by minuscorp** [comment]
Even Angular in their documentation snippet do [it](https://stackblitz.com/angular/ampvdvkdvoj?file=main.ts)

**Pull request merged**
