### PR TITLE
[WIP] Testing ci for ci don't merge

### PR DESCRIPTION
**Pull request by taquitos**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Still running 💛

**Comment by KrauseFx** [comment]
🚎 :trollface:

**Comment by taquitos** [comment]
Seesh, these tests take for-ev-er

**Comment by KrauseFx** [comment]
It's green 🍏

**Comment by taquitos** [comment]
CI server still having issues staying up. Will check it out soon

**Pull request closed without merging**
