### PR TITLE
Password Fields in Onboarding Forms

### PR DESCRIPTION
**Pull request by AndrewMcBurney**
Use password input fields instead of text fields in onboarding views for `ci_user_password` and `clone_user_api_token`.

### CODE REVIEW

**Comment by minuscorp** [comment]
Best PR, the next call won't show your password😇😂

**Comment by taquitos** [comment]
Looks like this PR want to merge into `fastlane:master` instead of `master`. Kinda confusing why we have `fastlane:master` branch.

**Comment by AndrewMcBurney** [comment]
This is weird because when I try to change base, it stays the same?

screen shot 2018-03-16 at 6 02 00 pm

**Comment by taquitos** [comment]
Weird, are you creating a branch directly on `fastlane/ci` or are you using a fork?

**Comment by AndrewMcBurney** [comment]
Oooooh, I know what's happening - because I'm creating a PR from my fork, it has `fastlane:master` as the branch.

See this PR for another example: https://github.com/fastlane/ci/pull/275

**Comment by taquitos** [comment]
I was curious because I JUST got `fastlane.ci` running for `fastlane.ci` and it didn't pick up this PR. So now I know why!

**Pull request merged**
