### PR TITLE
Added GitRepo utility decorators

### PR DESCRIPTION
**Pull request by minuscorp**
This PR is a piece of my older PR, deprecated by now I think.

Adds:

- `pull_before` decorator.
- `commit_after` decorator.

### CODE REVIEW

**Comment by snatchev** [comment]
@minuscorp sweet code!
Before making moves on this PR I would like to discuss the need that this code addresses. It would be nice to either 1.) have it used by another class or 2.) have a discussion about its future use and why we need it now. I apologize if this was already captured in another PR and I have missed it.

**Comment by taquitos** [comment]
Let's wait to merge this until we have another PR that utilizes this new functionality 👍

**Comment by minuscorp** [comment]
I'd like to get this merged so I can move towards applying it into the codebase if that's ok with you 😄

**Comment by taquitos** [comment]
I think it would be helpful if you could actually add in the usage you'd like inside this PR. That way we can have a working example.

**Comment by minuscorp** [comment]
I'll try to get this implemented soon!

**Comment by KrauseFx** [comment]
Moving over to https://github.com/fastlane/ci/pull/459

**Pull request closed without merging**
