### PR TITLE
#262 Unique new repo URL

### PR DESCRIPTION
**Pull request by viktorasl**
Hello 👋 

This is my first try to contribute to an amazing fastlane toolchain.

The first commit is a fix which prints actual file path (the issue was that actual path is `~/.fastlane/.keys`). The drawback is that is prints absolute path (not relative to HOME); looks verbose but I didn't find an easy way to print path relative to HOME.

The second commit is an implementation of #262. I went an easy way and in post action I've added two additional standalone fields. I did not want to extend `GitRepoConfig` with additional two fields as it might impact other places in the code, especially as those two fields currently required only for project import. Any comments on that are highly appreciated.

Probably I could've done something not by the book of guidelines so I'll try to fix any

### CODE REVIEW

**Comment by viktorasl** [comment]
I signed it!

**Comment by taquitos** [comment]
@viktorasl thank you! Question: how did you go about testing this?

**Comment by viktorasl** [comment]
I tested it manually: onboarded repo from my list of GitHub repos. I did not see any unit/integration tests testing views and as I don't have much experience working with ruby and especially with sinatra I didn't introduced tests myself.

**Comment by taquitos** [comment]
Yeah, we don't have great test coverage at the moment.
Did you happen to test if you have 2 repos by the same name, but 2 different orgs, for example: one repo is your own repo, and the other is a repo by the same name belonging to an organization you're in?

**Comment by viktorasl** [comment]
I did test it now, works fine. Though I've noticed that list shows multiple same name repos so I've added an additional column indicating owner of the repo (an alternative would be to show full path in project name column like `organization_name/project_name`)

**Comment by minuscorp** [comment]
I've also addressed this in my PR, just in case someone thinks this was not in the agenda #283 I follow the same pattern `org/repo` 😁

**Comment by viktorasl** [comment]
Yeah, looks like I've implemented already partly closed issue 😁 I'm thinking.. shall I close it just to avoid merge conflicts?

**Comment by taquitos** [comment]
@viktorasl @minuscorp just going through some PRs, was wondering if there was anything left that this PR addresses, or if we should close it out. Thoughts?

**Comment by viktorasl** [comment]
The first commit kinda fixes path to `.keys` file, is it relevant? I could split just that commit into separate PR.

**Comment by taquitos** [comment]
@viktorasl oh yeah, good idea!

**Comment by taquitos** [comment]
@viktorasl heyo, that other PR is merged that you had broken out. Is there anything in this pr that you think should also be merged? If so, could you update this or let us know what you think would be best?

**Comment by viktorasl** [comment]
Nope, nothing left to split, thanks for your support! 🚀

**Comment by KrauseFx** [comment]
Looking at this, there seems to be one important piece missing still, being https://github.com/fastlane/ci/issues/262

**Comment by viktorasl** [comment]
Previously that was covered by @minuscorp in #283 but as it was split into smaller PR's I can't track if that is still covered, if not just ping me to bring my implementation back and that'll be done

**Comment by minuscorp** [comment]
I have this covered in #363 which depends on #360

**Comment by KrauseFx** [comment]
Ah, alright, thanks 👍

**Pull request closed without merging**
