### PR TITLE
[WIP] Rename environment_variable_service to dot_keys_variable_service

### PR DESCRIPTION
**Pull request by KrauseFx**
.keys manager is limited and only focuses on the non-user specific ENV variables. For all user managed ones, we're gonna use a new data source + service

More information: https://github.com/fastlane/ci/issues/643
We're gonna use the names `EnvironmentVariable` and `EnvironmentVariableService` for ENV variables that are provided by the user

### CODE REVIEW

**Comment by AndrewMcBurney** [comment]
Do we need to change `FastlaneCI.env` to `FastlaneCI.dot_keys`?  I agree with the incentive behind changing the name for `environment_variable_service`, but I kinda like having the `FastlaneCI.env`, because it's similar to the `Rails.env` convention.

I'm cool with the chages, but I just wanted to open a discussion and get your thoughts.

**Comment by KrauseFx** [comment]
> Do we need to change FastlaneCI.env to FastlaneCI.dot_keys?
I don't feel strongly about it, but if we keep it, it would be a combination of the dot envs, and the actual system-wide environment variables, right? This would then break where we use `FastlaneCI.env`

**Comment by KrauseFx** [comment]
Ugh, merge conflicts, no fun

**Comment by AndrewMcBurney** [comment]
Yeah, sorry Felix. My last PR merged changed a lot of the files you modified in this PR. 😳If you want me to resolve them, that's :100: too

**Comment by KrauseFx** [comment]
Alright, gonna tackle this tomorrow morning

**Comment by KrauseFx** [comment]
Closing this in favor of https://github.com/fastlane/ci/pull/739

**Pull request closed without merging**
