### PR TITLE
Implement build detail view

### PR DESCRIPTION
**Pull request by KrauseFx**
- User story https://github.com/fastlane/ci/blob/master/docs/use_cases/access_build_details.md
- Fixes https://github.com/fastlane/ci/issues/450

---

screenshot 2018-04-02 04 05 53

### CODE REVIEW

**Comment by taquitos** [comment]
Do you happen to have a screen shot?

**Comment by KrauseFx** [comment]
Alright, updated other parts of the code also 👍

**Comment by KrauseFx** [comment]
Ready for review

**Comment by KrauseFx** [comment]
Right now we assume the `.first` for each trigger.

**Comment by KrauseFx** [comment]
Not sure if it's worth spending extra time to also filter the extra metadata of a trigger, like the branch

**Pull request merged**
