### PR TITLE
Kick off builds for open prs that have no status on server start

### PR DESCRIPTION
**Pull request by taquitos**
Once the server starts, we should find all open prs that don't have a status yet.
Once we find them, create a build.

### CODE REVIEW

**Comment by nakhbari** [comment]
@taquitos Should there be a job trigger for this?

**Comment by KrauseFx** [comment]
@nakhbari like a UI element where you can trigger running over all open PRs without a status?

**Comment by nakhbari** [comment]
@KrauseFx All our other methods of running builds are gated by job triggers.

Nightly Trigger(X) -> automatically kicks off nightly builds on branch X
New Commit Trigger(X) -> automatically kicks off builds when there's a new commit on branch X

So for this, something like
Open PR Trigger(X) -> automatically kicks off builds on new open PRs on branch X


WDYT?

**Comment by taquitos** [comment]
@nakhbari `Open PR Trigger(X) -> automatically kicks off builds on new open PRs on branch X`
Is the same as `CommitJobTrigger` 😄 
PRs have a list of commits, and commits are required for `status` checks (PRs are just issues, and don't have a status associated with them).

**Pull request merged**
