### PR TITLE
Add initial support to Docker

### PR DESCRIPTION
**Pull request by adellibovi**
This solves  #296, it adds support to deploy fastlane.ci with "docker-compose up", currently it supports production mode only.

### CODE REVIEW

**Comment by dlackty** [comment]
I would suggest adding a [`.dockerignore`](https://github.com/sameersbn/docker-gitlab/blob/master/.dockerignore) file?

**Comment by adellibovi** [comment]
@dlackty what would you suggest to ignore? Currently, I would say that only `docs` folder could be ignored

**Comment by taquitos** [comment]
It might be helpful to add in some basic instructions on how to use it with docker for people who aren't familiar 👍

**Comment by taquitos** [comment]
@adellibovi I just pinging you on twitter 🎉

**Comment by adellibovi** [comment]
@taquitos good idea! I will modify the Readme to include instruction to run with Docker 😄

**Comment by adellibovi** [comment]
Made some changes on the `Readme`, please let me know how does that feels :)

**Comment by dlackty** [comment]
@adellibovi ah yes, you're right and I just forgot that. 
In the long term I guessed we might need to separate this project itself and configuration repo just like Match or Fastlane itself does.

**Pull request merged**
