### PR TITLE
Add overcommit

### PR DESCRIPTION
**Pull request by Ashraf-Ali-aa**
Summary:
Fixes https://github.com/fastlane/ci/issues/1001

* Add overcommit - https://github.com/brigade/overcommit
* Automatically run `rspec` and `rubocop`
* Run tests before pushing up changes

- [x] I have run `rspec` and corrected all errors
- [x] I have run `rubocop` and corrected all errors
- [x] I have tested this change locally and tried to launch the server as well as access a project, and with that at least one build
- [x] If there is an existing issue, make sure to add `Fixes ...` as part of the PR body to reference the issue you're solving

Example:
image

image

### CODE REVIEW

**Comment by Ashraf-Ali-aa** [comment]
I signed it!

**Comment by KrauseFx** [comment]
This looks legit, thanks for the PR. I'll change with my team-mates to see what they think 👍

**Comment by taquitos** [comment]
This looks cool to me. I love pre-commit checks 🎉

**Review by KrauseFx — APPROVED** [review]
Let's do this 👍

**Pull request merged**
