### PR TITLE
Initial fastlane visuals

### PR DESCRIPTION
**Pull request by KrauseFx**
Migrated over from https://github.com/fastlane/ci/pull/273

screen shot 2018-03-28 at 3 46 25 pm

---

screen shot 2018-03-28 at 3 51 05 pm

### CODE REVIEW

**Comment by taquitos** [comment]
This is annoying, but:
```  1) FastlaneCI docs app/features/fastfile_editor has a README.md
     Failure/Error: expect(content).to start_with("# `#{feature_directory.gsub('app/', '')}`")
       expected "This directory contains all code related to rendering and editing a `Fastfile`\n" to start with "# `features/fastfile_editor`"
     # ./spec/docs_spec.rb:11:in `block (4 levels) in <top (required)>'
```

fastlane.ci seems to be stuck on a branch or something so the wrong shas are getting tested

**Comment by taquitos** [comment]
👎 
2018-03-28 00:16:46 - NameError - undefined local variable or method `fastfile_parser' for #<FastlaneCI::ProjectController:0x007fb1a2a70868>
Did you mean?  fastfile_path:
	/Users/jliebowitz/dev/ci/app/features/project/views/project.erb:23:in `block in singleton class'
	/Users/jliebowitz/dev/ci/app/features/project/views/project.erb:-9:in `instance_eval'
	/Users/jliebowitz/dev/ci/app/features/project/views/project.erb:-9:in `singleton class'
	/Users/jliebowitz/dev/ci/app/features/project/views/project.erb:-12:in `__tilt_70200405793300'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:839:in `render'
	/Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:682:in `erb'
	/Users/jliebowitz/dev/ci/app/features/project/project_controller.rb:193:in `block in <class:ProjectController>'

**Comment by KrauseFx** [comment]
This is work in progress, haven't committed all the files yet

**Comment by KrauseFx** [comment]
I'd be ok with merging this now - this will need to be updated slightly once https://github.com/fastlane/ci/pull/363 is ready & merged 👍

**Pull request merged**
